# Generated by Django 3.2.13 on 2022-05-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBeneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoriabeneficio', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria Beneficio',
                'verbose_name_plural': 'Categoria Beneficio',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPreferenciaPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoriapreferencia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria Preferencia Personal',
                'verbose_name_plural': 'Categoria Preferencia Personal',
            },
        ),
        migrations.CreateModel(
            name='EmpresaBeneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreempresabeneficio', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Empresa Beneficio',
                'verbose_name_plural': 'Empresa Beneficio',
            },
        ),
        migrations.CreateModel(
            name='EmpresaTitular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreempresatitular', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Empresa Titular',
                'verbose_name_plural': 'Empresa Titular',
            },
        ),
        migrations.CreateModel(
            name='IndustriaEmpresaTitular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreindustria', models.CharField(max_length=30)),
                ('descripcionindustria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'IdustriaEmpresaTitular',
                'verbose_name_plural': 'IdustriaEmpresaTitular',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaPersonal',
            fields=[
                ('nombrepreferenciapersonal', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('idcategoriapreferenciapersonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriapreferenciapersonal')),
            ],
            options={
                'verbose_name': ' Preferencia Personal',
                'verbose_name_plural': 'Preferencia Personal',
            },
        ),
        migrations.CreateModel(
            name='ProductoEmpresaTitular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('idempresatitular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresatitular')),
            ],
            options={
                'verbose_name': 'Produco Empresa Titular',
                'verbose_name_plural': 'Producto Empresa Titular',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipousuario', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Usuario',
                'verbose_name_plural': 'Tipo Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('idtipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
            options={
                'verbose_name': ' Usuario',
                'verbose_name_plural': ' Usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioProductoEmpresaTitular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idproductoempresatitular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productoempresatitular')),
                ('usuariio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Producto Empresa Titular',
                'verbose_name_plural': 'Usuario Producto Empresa Titular',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preferenciapersonal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Preferencia',
                'verbose_name_plural': 'Usuario Preferencia',
            },
        ),
        migrations.CreateModel(
            name='EmpresaTitularBeneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebeneficio', models.CharField(max_length=30)),
                ('fechainicio', models.DateField()),
                ('fechatermino', models.DateField()),
                ('checklu', models.BooleanField()),
                ('checkma', models.BooleanField()),
                ('checkmi', models.BooleanField()),
                ('checkju', models.BooleanField()),
                ('checkvi', models.BooleanField()),
                ('checksa', models.BooleanField()),
                ('checkdo', models.BooleanField()),
                ('idcategoriabeneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriabeneficio')),
                ('idempresabeneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresabeneficio')),
                ('idproductoempresatitular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productoempresatitular')),
            ],
            options={
                'verbose_name': 'Empresa Titular Beneficio',
                'verbose_name_plural': 'Empresa Titular Beneficio',
            },
        ),
        migrations.AddField(
            model_name='empresatitular',
            name='idindustriaempresatitular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.industriaempresatitular'),
        ),
    ]
