# Generated by Django 3.2.13 on 2022-05-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioproductoempresatitular',
            old_name='usuariio',
            new_name='usuario',
        ),
    ]
